name: Validate Cloudformation Template
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:

  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:

      - name: Check out code into the directory
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Validate template
        run: aws cloudformation validate-template --template-body=file://./templates/vpn.yaml