name: Validate Cloudformation Template
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:

  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:

      - name: Check out code into the directory
        uses: actions/checkout@v2

      - name: Validate template
        run: aws cloudformation validate-template --template-body=file://./templates/vpn.yaml --region=ap-southeast-2